const mangaTitles = [
  "unordinary",
  "Shingeki no Kyojin",
  "solo leveling",
  "Shokugeki no Souma",
  "Haikyuu",
  "My Hero Academia",
  "one piece",
  "dr. stone",
  "the promised neverland",
  "burning effect",
  "black clover",
  "beautiful legends",
  "samurai 8",
  "the god of high school",
  "the gamer",
  "peerless dad",
  "fight class 3",
  "spy x family",
  "gokushufudou",
  "chainsawman",
  "The Scholar's Reincarnation",
  "Tate no Yuusha no Nariagari",
  "To You, The Immortal",
  "Tower of God",
  "Akagami no Shirayukihime",
  "A Returner’s Magic Should be Special",
  "Baby Steps",
  "Jujutsu Kaisen",
  "The Wrong Way to use Healing Magic",
  "Act-Age",
  "Dad is a Hero, Mom is a Spirit, I'm a Reincarnator",
  "Heart Gear",
  "Isekai de Tadahitori No Manono Tsukai ~ Tenshoku Shitara Maou ni Machigawa Remashita",
  "Tensei Shitara Slime Datta Ken",
  "Chainsaw Man",
  "Demon Slayer: Kimetsu no Yaiba"
]

export default mangaTitles;
